services:
  - type: web
    name: tv-to-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: true
      - key: TELEGRAM_CHAT_ID
        sync: true
